// ═══ SPRITES MODULE ═══
// 24×32 pixel art sprites for all stages and classes

const S0 = {
  name: 'E-RANK SCRUB',
  desc: '$400 gold. No armour. No plan. Just a guy with a cat and a dream.',
  rank: 'E',
  pal: {
    h: '#9a6840', H: '#6a4420', j: '#c08850', J: '#b07848',
    s: '#f0c898', S: '#dab080', k: '#c09060',
    e: '#181830', w: '#f0e8e0', m: '#d07868',
    a: '#58983c', A: '#3c7828', i: '#70b050', I: '#88c868',
    p: '#4a6830',
    t: '#8a6840', T: '#604828',
    b: '#7a6848', B: '#584830', n: '#987858',
    f: '#6a5030', F: '#483818',
  },
  grid: [
    '........................',
    '......HHHHHHHH..........',
    '.....HhhhhhhhHH.........',
    '....HhhjjjjjhhHH........',
    '....HhhhhhhhhhhH........',
    '....JhhhhhhhhhhJ........',
    '....JhJjhhhJjhJ.........',
    '.....JssssssssJ.........',
    '.....kssssssssk.........',
    '.....kseswwsesk.........',
    '.....ksssssssSk.........',
    '.....kkssmmsSkk.........',
    '......ksSSSsk...........',
    '......IiaaaiI...........',
    '.....IiaaaaaiI..........',
    '.....IiaapaaiI..........',
    '.....AiaaaaaaIA.........',
    '.....AAaaaaaaAA.........',
    '......AAtTTtAA..........',
    '......AAtTTtAA..........',
    '.......ttTTtt...........',
    '......nBBbbBBn..........',
    '......BBBbbBBB..........',
    '......BBb..bBB..........',
    '......nBb..bBn..........',
    '.......fb..bf...........',
    '.....FFff..ffFF.........',
    '.....FFF....FFF.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ]
};

const S1 = {
  name: 'D-RANK RECRUIT',
  desc: 'First savings made. A dagger earned. The journey of discipline begins.',
  rank: 'D',
  pal: {
    h: '#9a6840', H: '#6a4420', j: '#c08850', J: '#b07848',
    s: '#f0c898', S: '#dab080', k: '#c09060',
    e: '#181830', w: '#f0e8e0', m: '#d07868',
    r: '#d83030', R: '#a82020',
    a: '#a88050', A: '#806030', i: '#c09860', I: '#d0a870',
    g: '#d8b838',
    t: '#705038', T: '#503020',
    b: '#7a6848', B: '#584830', n: '#987858',
    f: '#6a5030', F: '#483818',
    W: '#c0c8d8', X: '#dce4f0', Q: '#b8a030',
  },
  grid: [
    '........................',
    '......HHHHHHHH..........',
    '.....HhhhhhhhHH.........',
    '....HhhjjjjjhhHH........',
    '....RrrrrrrrrrrR........',
    '....JhJjhhhJjhJ.........',
    '....JhhhhhhhhhhJ........',
    '.....Jssssssssj.........',
    '.....kssssssssk.........',
    '.....kseswwsesk.........',
    '.....ksssssssSk.........',
    '.....kkssmmsSkk.........',
    '......ksSSSsk...........',
    '......IiaaaiI...........',
    '.....IiaaaaaiI..........',
    '.....AiaaTagaiA.........',
    '.....AAaaaaaaAA.........',
    '.....AAaaaaaaAA...X.....',
    '......AAtTTtAA....W.....',
    '......AAtTTtAA...WW.....',
    '.......ttTTtt...XWXQ....',
    '......nBBbbBBn...QQ.....',
    '......BBBbbBBB..........',
    '......BBb..bBB..........',
    '......nBb..bBn..........',
    '.......fb..bf...........',
    '.....FFff..ffFF.........',
    '.....FFF....FFF.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ]
};

const S2 = {
  name: 'C-RANK WARRIOR',
  desc: 'Marketing running. Code frozen. The warrior learns to fight smart, not pretty.',
  rank: 'C',
  pal: {
    c: '#8898b0', C: '#a0b0c8', d: '#6878a0', D: '#b8c8d8',
    s: '#f0c898', S: '#dab080', k: '#c09060',
    e: '#181830', w: '#f0e8e0', m: '#d07868',
    a: '#7888a0', A: '#607088', i: '#90a0b8', I: '#a8b8c8',
    g: '#d8b838', G: '#c0a028', Y: '#e8c848',
    T: '#4080c0', t: '#58a0d8',
    J: '#505868',
    b: '#586878', B: '#405060',
    f: '#4a5868', F: '#384050',
    W: '#c8d0e0', X: '#dce4f0', Q: '#c8a830',
  },
  grid: [
    '........................',
    '.......ddddddd..........',
    '......dDDDDDDDd.........',
    '.....dDCCCCCCCDd........',
    '.....dDCCCCCCCDd........',
    '.....dcCDDDDCcdd........',
    '.....dccCCCCccd.........',
    '......dsssssssd.........',
    '......kssssssskd........',
    '......kseswwseSk........',
    '......ksssssssSk........',
    '......kkssmmsSkk........',
    '....YGgiaaaiIgGY....X...',
    '...YGIiiaaaaaiIGY..WX...',
    '...GAIiAAAAAAAAIGk.WX...',
    '...GAIiAAAAAAAAIGk.WXX..',
    '...GAAAAAATTAAAAGk.WXX..',
    '....GAAAAATTAAAAGkQWWQ..',
    '....GAAAAAJJAAAAGk.QQQ..',
    '.....AAAIttttIAAA..QQ...',
    '......AAtTTTTtAA........',
    '......BBBbbBBBBB........',
    '......BBBbbBBBBb........',
    '......BBb...bBBb........',
    '......Bb.....bBb........',
    '.....FFf.....fFF........',
    '.....FFF.....FFF........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ]
};

const S3 = {
  name: 'B-RANK KNIGHT',
  desc: 'Revenue flowing. Savings real. The knight stands armoured at last.',
  rank: 'B',
  pal: {
    o: '#384058',
    c: '#98a8c0', C: '#b0c0d0', d: '#7888a0', D: '#c8d0e0',
    p: '#d03838', P: '#b02020',
    v: '#3070d8', V: '#2050a8',
    s: '#d0d8e8', S: '#e0e8f0', a: '#b0b8d0', A: '#98a0b8',
    g: '#e8c840', G: '#d0a828', Y: '#f0d858',
    T: '#3070c8', t: '#4890e0',
    J: '#485060', H: '#8898b0',
    R: '#2848a8', r: '#3060c0',
    L: '#7888a0', l: '#90a0b8',
    K: '#506878', k: '#607888',
    W: '#d0d8e8', X: '#e8f0ff', Q: '#d8c040',
  },
  grid: [
    '........................',
    '.......ppppp............',
    '......PPpppPP...........',
    '......oPPpPPo...........',
    '.....oDDDDDDDo..........',
    '.....oCCCCCCCo..........',
    '.....oCCDDDCCo..........',
    '.....oVVVvvVVo..........',
    '......oCCCCCo...........',
    '......ooCCCoo...........',
    '...YGgaSSSSSSagGY.......',
    '..YGgaSSSSSSSSSgGY..X...',
    '..GgAaSSSSSSSsaAgG..WX..',
    '..GHAASSSSSSSSSAHG..WX..',
    '..GHAASSSSSSSSAAHG..WX..',
    '..GHAASSSSSSSSAAHG.WXX..',
    '...HAASSSSSSSAAAH.QWWQ..',
    '...HAAJJgJJgJJAAH..QQ...',
    '....AATtttttTTAAA..QQ...',
    '.R..AATtttttTTAA........',
    '.R..AATTTaTTTTAA........',
    '.R...AaSSSSSsaA.........',
    '.r...llAAAAAAll.........',
    '.r...llA...Aall.........',
    '.r...kk.....kkl.........',
    '.....kk.....kkK.........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ]
};

const S4 = {
  name: 'A-RANK CHAMPION',
  desc: 'Side income live. Runway built. The cape earned through months of grinding.',
  rank: 'A',
  pal: {
    o: '#384058',
    c: '#a8b8d0', C: '#c0c8e0', d: '#8898b0', D: '#d0d8e8',
    p: '#e04040', P: '#c82828',
    v: '#3878e0', V: '#2858c0',
    s: '#d0d8e8', S: '#e0e8f0', a: '#b8c0d8', A: '#a0a8c0',
    g: '#f0d050', G: '#d8b838', Y: '#f8e068',
    R: '#b02028', r: '#c83030', q: '#d84040',
    T: '#3070c8', t: '#4890e0',
    J: '#506070', H: '#8898b0',
    L: '#7888a0', l: '#90a0b8',
    K: '#506878', k: '#607888',
    W: '#d8e0f0', X: '#e8f0ff', Q: '#e0c840', Z: '#80c0f8',
  },
  grid: [
    '........................',
    '......PPPPppp...........',
    '.....PPpppppp...........',
    '......oPPpPPo...........',
    '.....oDDDDDDDo..........',
    '.....oCCCCCCCo..........',
    '.....oCCDDDCCo..........',
    '.R...oVVVvvVVo..........',
    '.R....oCCCCCo...........',
    '.R....ooCCCoo...........',
    '.RYGgaSSSSSSagGY........',
    '.RYGgaSSSSSSSSSgGY......',
    '.R.GgAaSSSSSSsaAgG..Z...',
    '.r.GHAASSSSSSSSSAHGZWX..',
    '.r.GHAASSSSSSSSAAHGZWX..',
    '.r.GHAASSSSSSSSAAHGZWXX.',
    '.r..HAASSSSSSSAAAH.QWWQ.',
    '.q..HAAJJgJJgJJAAH.QQQ..',
    '.q...AATtttttTTAAA..QQ..',
    '.q...AATtttttTTAA.......',
    '.q...AATTTaTTTTAA.......',
    '.q....AaSSSSSsaA........',
    '..q...llAAAAAAll........',
    '..q...llA...Aall........',
    '..q...kk.....kkl........',
    '......kk.....kkK........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ]
};

const S5 = {
  name: 'S-RANK SOVEREIGN',
  desc: 'Freedom achieved. You work for yourself. The system acknowledges your awakening.',
  rank: 'S',
  pal: {
    o: '#384058',
    c: '#b8c0d8', C: '#c8d0e8', d: '#98a8c0', D: '#d8e0f0',
    n: '#f0d848', N: '#e0c030', M: '#d0a828',
    v: '#40a0f0', V: '#3080d0',
    s: '#d8e0f0', S: '#e8f0f8', a: '#c0c8e0', A: '#a8b0c8',
    g: '#f8e060', G: '#e0c840', Y: '#fff070',
    R: '#4828a0', r: '#5838b8', q: '#6848c8',
    T: '#3070c8', t: '#4890e0',
    J: '#506070', H: '#8898b0',
    L: '#8090a8', l: '#90a0b8',
    K: '#506878', k: '#607888',
    W: '#e0e8ff', X: '#f0f8ff', Q: '#e8d048', Z: '#98c8ff',
    u: '#5080e8', U: '#3868d0',
  },
  grid: [
    '....N.nMNMn.N...........',
    '.....NnMMMnNN...........',
    '......oNMNo.............',
    '......oDDDDDDo..........',
    '.....oDDDDDDDDo.........',
    '.....oCCCCCCCCo.........',
    '.....oCCDDDCCCo.........',
    '.R...oVVVvvVVVo.........',
    '.R....oCCCCCCo..........',
    '.R....ooCCCCoo..........',
    '.RYGgaSSSSSSSSagGY......',
    '.RYGgaSSSSSSSSSSgGY.....',
    '.R.GgAaSSSSSSSSaAgGuZ...',
    '.r.GHAASSSSSSSSSSAHuZWX.',
    '.r.GHAASSSSSSSSSAAHUZWX.',
    '.q.GHAASSSSSSSSAAaHUZWXX',
    '.q..HAASSSSSSSSaaaHQWWQu',
    '.q..HAAJJgJJgJJAAH.QQQQ.',
    '.q...AATtttttTTAAA..QQ..',
    '.q...AATtttttTTAA.......',
    '.q...AATTTaTTTTAA.......',
    '..q...AaSSSSSsaA........',
    '..q...llAAAAAAll........',
    '..q...llA...Aall........',
    '..q...kk.....kkl........',
    '......kk.....kkK........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ]
};

export const STAGES = [S0, S1, S2, S3, S4, S5];

// ═══ CLASS-SPECIFIC SPRITES ═══
export const CLASS_SPRITES = {
  knight: {
    3: {
      pal: {
        o: '#182038', c: '#98a8c0', C: '#b0c0d0', d: '#8090a8', D: '#c8d0e0',
        p: '#d83838', P: '#b02020', v: '#2858b8', V: '#3870d0',
        s: '#c0c8d8', S: '#d0d8e8', a: '#a0a8b8', A: '#8898a8',
        g: '#e8c038', G: '#d0a820', Y: '#f0d048',
        T: '#e0e8f0', t: '#d0d8e0', J: '#505868', H: '#7080a0',
        L: '#8090a0', l: '#90a0b0', K: '#506070', k: '#607080',
        W: '#d0d8e8', X: '#e0e8f0', Q: '#c0c8d8',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '........................',
        '.......ppppp............',
        '......PPpppPP...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.....oVVVVVVVo..........',
        '......odddddo...........',
        '......zzFFFzz...........',
        '.YGGgsSSSSSSSsgGGY.X....',
        '.YGGsSSSSSSSSSSSgGYWX...',
        '..GGAaSSSSSSSSSaAGGkWX..',
        '..GHAASSSSSSSSSAAHGkWX..',
        '..GHAASSSSSSSSAAaHGkWX..',
        '..GHAASSSSSSSSSAAHGQWXQ.',
        '...HAAJgJJJJgJJAAH..QQ..',
        '...HAAStTTTtSAAAH..QQ...',
        '....AAtTTTTTtAAAH.......',
        '....AATTTaTTTTAA........',
        '.....AaSSSSSsaA.........',
        '.....llAAAAAAll.........',
        '.....llA...Aall.........',
        '.....kk.....kkl.........',
        '.....KK.....KKK.........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#182038', c: '#a0b0c8', C: '#b8c8d8', d: '#8898b0', D: '#d0d8e8',
        p: '#e04040', P: '#c02828', v: '#3060c0', V: '#4070d0',
        s: '#c8d0e0', S: '#d8e0f0', a: '#a8b0c0', A: '#98a0b0',
        g: '#f0c840', G: '#d8b028', Y: '#f8d050',
        R: '#204898', r: '#2858a8', q: '#3068b8',
        T: '#e8f0f8', t: '#d8e0f0', J: '#5a6070', H: '#7888a8',
        L: '#8898a8', l: '#98a8b8', K: '#586878', k: '#687888',
        W: '#d0d8e8', X: '#e0e8f0', Q: '#c0c8d8', Z: '#80a8e0',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '......PPPPPpp...........',
        '.....PPppppppp..........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVvvVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGY.Z.....',
        '.RYGGsSSSSSSSSSgGYZWX...',
        '.R.GGAaSSSSSSSsaAgGZWX..',
        '.r.GHAASSSSSSSSSAHGZWX..',
        '.r.GHAASSSSSSSSAAHGZWX..',
        '.r.GHAASSSSSSSSAAHGZWX..',
        '.q..HAASSSSSSSAAAH.QWXQ.',
        '.q..HAAJgJJJJgJAAH..QQQ.',
        '.q...AAtTTTTtAAAH...QQ..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#182038', c: '#a8b8d0', C: '#c0c8e0', d: '#9098b8', D: '#d0d8f0',
        n: '#e8d040', N: '#d8c028', M: '#c8a820',
        v: '#3870e0', V: '#2860d0',
        s: '#d0d8e8', S: '#e0e8f8', a: '#b0b8c8', A: '#a0a8b8',
        g: '#f8d040', G: '#e0b828', Y: '#fff050',
        R: '#205080', r: '#3060a0', q: '#4070b0',
        T: '#f0f8ff', t: '#e0e8f8', J: '#606878', H: '#8090b8',
        L: '#9098b0', l: '#a0a8b8', K: '#607080', k: '#707888',
        W: '#d8e0f0', X: '#e8f0ff', Q: '#c8d0e8', Z: '#90b8f0',
        u: '#4080e0', U: '#3070d0',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVvvVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGYuZX....',
        '.RYGGsSSSSSSSSSgGUZWX...',
        '.R.GGAaSSSSSSSsaAgUZWX..',
        '.r.GHAASSSSSSSSSAHUZWX..',
        '.r.GHAASSSSSSSSAAHUZWX..',
        '.q.GHAASSSSSSSSAAHGUZWX.',
        '.q..HAASSSSSSSAAAH.QWXQ.',
        '.q..HAAJgJJJJgJAAH.QQQQ.',
        '.q...AAtTTTTtAAAH..QQ...',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  pyromancer: {
    3: {
      pal: {
        o: '#180808', c: '#c04820', C: '#d85830', d: '#a03818', D: '#e06838',
        p: '#f08030', P: '#d06020', v: '#f09030', V: '#e08020',
        s: '#d05820', S: '#e06830', a: '#b04818', A: '#a03818',
        g: '#f0a020', G: '#d08818', Y: '#f8b030',
        T: '#c04820', t: '#d05830', J: '#804020', H: '#c05828',
        L: '#704020', l: '#805030', K: '#603020', k: '#703828',
        W: '#f09030', X: '#f8a040', Q: '#e07828',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '........................',
        '......oDDDDDDo..........',
        '.....oCCCCCCCCo.........',
        '.....oCCCCCCCCo.........',
        '.....VVvvCCvvVV.........',
        '.....oCCCCCCCCo.........',
        '......offffffo..........',
        '......zffffffzz.........',
        '......zfewwfeFzz........',
        '......zffffffFz.........',
        '......zzfmmfFzz.........',
        '.......zzFFzz...........',
        '...YGgsSSSSSsgGY........',
        '..YGgsSSSSSSSSSgGY......',
        '..GgAaSSSJJJSSaAgG..XX..',
        '..GHAASJJJJJJSAAHGk.XX..',
        '..GHAASJJJJJJSAAHGk.WW..',
        '...HAASStttSSAAAH...W...',
        '...HAAStTTTTtSAAH..Q....',
        '....AAtTTTTTTtAAA.......',
        '....AAtTTTTTTtAA........',
        '.....LlllAllllL.........',
        '.....LlllAllllL.........',
        '.....Ll.....llL.........',
        '.....kk.....kkK.........',
        '.....KK.....KKK.........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#180808', c: '#d05828', C: '#e06838', d: '#b04820', D: '#f07848',
        p: '#f09030', P: '#e07820', v: '#f0a030', V: '#e09020',
        s: '#e06828', S: '#f07838', a: '#c05820', A: '#b04818',
        g: '#f8b030', G: '#e09820', Y: '#ffb840',
        R: '#d04018', r: '#e05028', q: '#f06038',
        T: '#d05828', t: '#e06838', J: '#904828', H: '#d06830',
        L: '#805030', l: '#906040', K: '#704030', k: '#804038',
        W: '#f8a040', X: '#ffb050', Q: '#e88030', Z: '#ffb840',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '......PPPPppp...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....VVvvCCvvVV.........',
        '.....oCCCCCCCCo.........',
        '.R....offffffo..........',
        '.R....zffffffzz.........',
        '.R....zfewwfeFzz........',
        '.R....zffffffFz.........',
        '.R....zzfmmfFzz.........',
        '.R.YGGsSSSSSsSGGY.......',
        '.r.YGgsSSSSSSSSSgGY.....',
        '.r.GgAaSJJJJJSaAgG..ZXX.',
        '.r.GHAAJJJJJJJAAAHG.ZXX.',
        '.q.GHAASStttSSAAHGk..WW.',
        '.q..HAASStTTtSSAAH...W..',
        '.q..HAAtTTTTTTtAAH..Q...',
        '.q...AAtTTTTTTtAAA......',
        '.q...AATTTaTTTTAA.......',
        '..q...AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#180808', c: '#e06838', C: '#f07848', d: '#c05828', D: '#ff8858',
        n: '#ffb030', N: '#f09820', M: '#e08818',
        v: '#ffb040', V: '#f0a030',
        s: '#f07838', S: '#ff8848', a: '#d06828', A: '#c05820',
        g: '#ffb030', G: '#f09820', Y: '#ffc840',
        R: '#e05030', r: '#f06040', q: '#ff7050',
        T: '#e06838', t: '#f07848', J: '#a05030', H: '#e07838',
        L: '#906040', l: '#a07050', K: '#804838', k: '#907048',
        W: '#ffb050', X: '#ffc060', Q: '#f09030', Z: '#ffd070',
        u: '#f09830', U: '#e08820',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....VVvvCCvvVV.........',
        '.....oCCCCCCCCo.........',
        '.R....offffffo..........',
        '.R....zffffffzz.........',
        '.R....zfewwfeFzz........',
        '.R....zffffffFz.........',
        '.R....zzfmmfFzz.........',
        '.RYGGgsSSSSSsSGGY.......',
        '.r.YGgsSSSSSSSSSgGY.....',
        '.r.GgAaSJJJJJSaAgGuZX...',
        '.r.GHAAJJJJJJJAAAHUZWX..',
        '.q.GHAASStttSSAAHGUZWX..',
        '.q..HAASStTTtSSAAH.QWWQ.',
        '.q..HAAtTTTTTTtAAH..QQQ.',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '..q...AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  sorcerer: {
    3: {
      pal: {
        o: '#0a0818', c: '#6040a0', C: '#7858b8', d: '#5030a0', D: '#8868c8',
        p: '#c080f0', P: '#a060e0', v: '#a070e0', V: '#8050d0',
        s: '#6848a8', S: '#7858b8', a: '#5838a0', A: '#483898',
        g: '#d0a0f0', G: '#b080e0', Y: '#e0b0ff',
        T: '#704090', t: '#805098', J: '#504870', H: '#7060a0',
        L: '#605878', l: '#707090', K: '#504870', k: '#605878',
        W: '#c090e8', X: '#d0a0f8', Q: '#a878d8',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '........................',
        '......oDDDDDDo..........',
        '.....oCCCCCCCCo.........',
        '.....oCCCCCCCCo.........',
        '.....VVvvCCvvVV.........',
        '.....oCCCCCCCCo.........',
        '......offffffo..........',
        '......zffffffzz.........',
        '......zfewwfeFzz........',
        '......zffffffFz.........',
        '......zzfmmfFzz.........',
        '.......zzFFzz...........',
        '...YGgsSSSSSsgGY........',
        '..YGgsSSSSSSSSSgGY......',
        '..GgAaSSSJJJSSaAgG..XX..',
        '..GHAASJJJJJJSAAHGk.XX..',
        '..GHAASJJJJJJSAAHGk.WW..',
        '...HAASStttSSAAAH...W...',
        '...HAAStTTTTtSAAH..Q....',
        '....AAtTTTTTTtAAA.......',
        '....AAtTTTTTTtAA........',
        '.....LlllAllllL.........',
        '.....LlllAllllL.........',
        '.....Ll.....llL.........',
        '.....kk.....kkK.........',
        '.....KK.....KKK.........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#0a0818', c: '#7050b0', C: '#8868c8', d: '#6040a8', D: '#9878d8',
        p: '#d090f8', P: '#b070e8', v: '#b080e8', V: '#9068d8',
        s: '#7858b0', S: '#8868c0', a: '#6848a8', A: '#5838a0',
        g: '#e0b0f8', G: '#c090e8', Y: '#f0c0ff',
        R: '#503090', r: '#6040a0', q: '#7050b0',
        T: '#805098', t: '#906090', J: '#605888', H: '#8070b8',
        L: '#706890', l: '#8078a0', K: '#607090', k: '#708098',
        W: '#d0a0f8', X: '#e0b0ff', Q: '#c090e8', Z: '#e8c0ff',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '......PPPPppp...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....VVvvCCvvVV.........',
        '.....oCCCCCCCCo.........',
        '.R....offffffo..........',
        '.R....zffffffzz.........',
        '.R....zfewwfeFzz........',
        '.R....zffffffFz.........',
        '.R....zzfmmfFzz.........',
        '.R.YGGsSSSSSsSGGY.......',
        '.r.YGgsSSSSSSSSSgGY.....',
        '.r.GgAaSJJJJJSaAgG..ZXX.',
        '.r.GHAAJJJJJJJAAAHG.ZXX.',
        '.q.GHAASStttSSAAHGk..WW.',
        '.q..HAASStTTtSSAAH...W..',
        '.q..HAAtTTTTTTtAAH..Q...',
        '.q...AAtTTTTTTtAAA......',
        '.q...AATTTaTTTTAA.......',
        '..q...AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#0a0818', c: '#8060c0', C: '#9878d0', d: '#7050b0', D: '#a888e0',
        n: '#e0c0ff', N: '#c0a0f0', M: '#a080e0',
        v: '#c0a0f0', V: '#a080e0',
        s: '#8868c0', S: '#9878d0', a: '#7858b0', A: '#6848a8',
        g: '#f0c0ff', G: '#d0a0f0', Y: '#ffcfff',
        R: '#6040a8', r: '#7050b8', q: '#8060c0',
        T: '#9060a8', t: '#a070b8', J: '#706898', H: '#9080c0',
        L: '#8078a8', l: '#9088b8', K: '#708098', k: '#8090a8',
        W: '#e0b0ff', X: '#f0c0ff', Q: '#d0a0f0', Z: '#f8d0ff',
        u: '#9070d0', U: '#7858c0',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....VVvvCCvvVV.........',
        '.....oCCCCCCCCo.........',
        '.R....offffffo..........',
        '.R....zffffffzz.........',
        '.R....zfewwfeFzz........',
        '.R....zffffffFz.........',
        '.R....zzfmmfFzz.........',
        '.RYGGgsSSSSSsSGGY.......',
        '.r.YGgsSSSSSSSSSgGY.....',
        '.r.GgAaSJJJJJSaAgGuZX...',
        '.r.GHAAJJJJJJJAAAHUZWX..',
        '.q.GHAASStttSSAAHGUZWX..',
        '.q..HAASStTTtSSAAH.QWWQ.',
        '.q..HAAtTTTTTTtAAH..QQQ.',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '..q...AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  mage: {
    3: {
      pal: {
        o: '#101828', c: '#2060c0', C: '#3070d0', d: '#1850a8', D: '#4080e0',
        p: '#5090f0', P: '#4080e0', v: '#3880f0', V: '#3070e0',
        s: '#2868c8', S: '#3878d8', a: '#1858a8', A: '#1050a0',
        g: '#50a0e0', G: '#4090d0', Y: '#60b0f0',
        T: '#184880', t: '#204890', J: '#304870', H: '#2858a0',
        L: '#304870', l: '#405880', K: '#203858', k: '#304868',
        W: '#80c0f8', X: '#90d0ff', Q: '#70b0e8',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '........................',
        '.......PPPPppp..........',
        '......PPPPPPPPo.........',
        '.....oDDDDDDDDDo........',
        '.....oCCCCCCCCCo........',
        '.....oCDDDDDDCo.........',
        '......offffffo..........',
        '......zffffffzz.........',
        '......zfewwfeFzz........',
        '......zffffffFz.........',
        '......zzfmmfFzz.........',
        '.......zzFFzz...........',
        '...YGgsSSSSSsgGY..XX....',
        '..YGgsSSSSSSSSSgGY.WW...',
        '..GgAaSSSSSSSSSaAGkQW...',
        '..GHAASSSgSSSSAAHGkQW...',
        '..GHAASSSgSSSSAAHGkQW...',
        '...HAASStTTtSSAAAHkQW...',
        '...HAAStTTTTtSAAH..QW...',
        '....AAtTTTTTTtAAA..Q....',
        '....AAtTTTTTTtAA........',
        '.....LlllAllllL.........',
        '.....LlllAllllL.........',
        '.....Ll.....llL.........',
        '.....kk.....kkK.........',
        '.....KK.....KKK.........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#101828', c: '#2868c8', C: '#3878d8', d: '#2060b8', D: '#4888e8',
        p: '#60a0f0', P: '#5090e8', v: '#4888f0', V: '#4080e8',
        s: '#3070c8', S: '#4080d8', a: '#2060a8', A: '#1850a0',
        g: '#60b0f0', G: '#50a0e0', Y: '#70c0f8',
        R: '#102060', r: '#182870', q: '#203080',
        T: '#205898', t: '#306890', J: '#405878', H: '#3068b0',
        L: '#405880', l: '#506890', K: '#304868', k: '#406078',
        W: '#90c8f8', X: '#a0d8ff', Q: '#80b8e8', Z: '#b0e0ff',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '......PPPPPPo...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDDo.........',
        '.....oCCCCCCCCCo........',
        '.....oCDDDDDDCCo........',
        '.R....oVVVvvVVo.........',
        '.R....offffffo..........',
        '.R....zfewwfeFzz........',
        '.R....zffffffFz.........',
        '.R....zzfmmfFzz.........',
        '.RYGGgsSSSSSsSGGY.XX....',
        '.r.YGgsSSSSSSSSSgGYWW...',
        '.r.GgAaSSSSSSSSSaAGZQW..',
        '.r.GHAASSSgSSSSAAHGZQW..',
        '.q.GHAASSSgSSSSAAHGkQW..',
        '.q..HAASStTTtSSAAH..QW..',
        '.q..HAAStTTTTtSAAH..QW..',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '..q...AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#101828', c: '#3070c8', C: '#4080d8', d: '#2868b8', D: '#5090e8',
        n: '#70c0f8', N: '#60b0e8', M: '#50a0d8',
        v: '#5090f0', V: '#4888e8',
        s: '#3878d0', S: '#4888e0', a: '#3070c0', A: '#2860b0',
        g: '#70c0f8', G: '#60b0e8', Y: '#80d0ff',
        R: '#182870', r: '#203080', q: '#284090',
        T: '#306898', t: '#407098', J: '#506888', H: '#4070b8',
        L: '#506890', l: '#607098', K: '#406078', k: '#507088',
        W: '#a0d0ff', X: '#b0e0ff', Q: '#90c0e8', Z: '#c0f0ff',
        u: '#5090e0', U: '#4080d0',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDDo.........',
        '.....oCCCCCCCCCo........',
        '.....oCDDDDDDCCo........',
        '.R...oVVVvvVVVo.........',
        '.R....offffffo..........',
        '.R....zfewwfeFzz........',
        '.R....zffffffFz.........',
        '.R....zzfmmfFzz.........',
        '.RYGGgsSSSSSsSGGY.......',
        '.r.YGgsSSSSSSSSSgGY.....',
        '.r.GgAaSSSgSSSSSaAGuZX..',
        '.r.GHAASSSgSSSSAAHGUZWX.',
        '.q.GHAASStTTtSSAAHGkQWX.',
        '.q..HAASStTTTtSAAH..QWX.',
        '.q..HAAStTTTTTtAAH..QQ..',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '..q...AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  warrior: {
    3: {
      pal: {
        o: '#1a1820', c: '#808890', C: '#98a0a8', d: '#687078', D: '#a8b0b8',
        p: '#c82828', P: '#a81818', v: '#d83828', V: '#c02818',
        s: '#808890', S: '#909898', a: '#707880', A: '#606870',
        g: '#c83020', G: '#a82018', Y: '#d84030',
        T: '#303030', t: '#404040', J: '#404040', H: '#606870',
        L: '#504848', l: '#605858', K: '#404040', k: '#504848',
        W: '#a8b0c0', X: '#c0c8d0', Q: '#c83020',
        f: '#f0c898', F: '#dab080', z: '#c09060',
      },
      grid: [
        '........................',
        '.......ppppp............',
        '......PPpppPP...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.....oVVVVVVVo..........',
        '......odddddo...........',
        '......zzFFFzz...........',
        '...YGgsSSSSSsgGY..X.....',
        '..YGgsSSSSSSSSSgGYWXX...',
        '..GgAaSSSSSSSSSaAgGWXX..',
        '..GHAASSSSSSSSSAAHGkXX..',
        '..GHAASSSSSSSSAAaHGkXX..',
        '..GHAASSSSSSSSAAHG.WXX..',
        '...HAASSSSSSSSaaAHQWWXQ.',
        '...HAAStTTTtSAAAH..QQQ..',
        '....AAtTTTTTtAAAH...Q...',
        '....AAtTTTTTtAAA........',
        '......LlllllllL.........',
        '......LlllAllllL........',
        '......Ll.....llL........',
        '......kk.....kkK........',
        '......KK.....KKK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#1a1820', c: '#909898', C: '#a8b0b8', d: '#788088', D: '#b8c0c8',
        p: '#d83838', P: '#c02828', v: '#e84030', V: '#d03020',
        s: '#909898', S: '#a0a8a8', a: '#808888', A: '#707878',
        g: '#d83828', G: '#c02818', Y: '#e84838',
        R: '#302828', r: '#403838', q: '#504848',
        T: '#383030', t: '#484040', J: '#484040', H: '#707878',
        L: '#585050', l: '#686060', K: '#484040', k: '#585050',
        W: '#b8c0d0', X: '#d0d8e0', Q: '#d83828', Z: '#e86050',
        f: '#f0c898', F: '#dab080', z: '#c09060',
      },
      grid: [
        '......PPPPppp...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGY..Z....',
        '.RYGgsSSSSSSSSSgGYZXX...',
        '.R.GgAaSSSSSSSsaAgGZXX..',
        '.r.GHAASSSSSSSSSAHGZWXX.',
        '.r.GHAASSSSSSSSAAHGZWXX.',
        '.r.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA...Q..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#1a1820', c: '#98a0a8', C: '#b0b8c0', d: '#889090', D: '#c0c8d0',
        n: '#d83828', N: '#c02018', M: '#a81810',
        v: '#e84838', V: '#d83028',
        s: '#a0a8a8', S: '#b0b8b8', a: '#909898', A: '#808888',
        g: '#e84030', G: '#d03028', Y: '#f05040',
        R: '#383030', r: '#484040', q: '#585050',
        T: '#403838', t: '#504848', J: '#504848', H: '#808888',
        L: '#605858', l: '#707070', K: '#504848', k: '#605858',
        W: '#c8d0d8', X: '#d8e0e8', Q: '#d83828', Z: '#f07060',
        u: '#c03028', U: '#a81818',
        f: '#f0c898', F: '#dab080', z: '#c09060',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGYuZ.....',
        '.RYGgsSSSSSSSSSgGUZXX...',
        '.R.GgAaSSSSSSSSaAgUZWXX.',
        '.r.GHAASSSSSSSSSAHUZWXX.',
        '.r.GHAASSSSSSSSAAHUZWXX.',
        '.q.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  thief: {
    3: {
      pal: {
        o: '#0a1008', c: '#304830', C: '#405840', d: '#284028', D: '#506850',
        p: '#506840', P: '#385030', v: '#405840', V: '#506850',
        s: '#385038', S: '#485848', a: '#304030', A: '#283828',
        g: '#506840', G: '#385030', Y: '#607850',
        T: '#384030', t: '#484838', J: '#384038', H: '#485848',
        L: '#404838', l: '#505848', K: '#384038', k: '#484840',
        W: '#708858', X: '#809860', Q: '#607848',
        f: '#e0b888', F: '#c8a070', z: '#a88058',
      },
      grid: [
        '........................',
        '.......ppppp............',
        '......PPpppPP...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.....oVVVVVVVo..........',
        '......odddddo...........',
        '......zzFFFzz...........',
        '...YGgsSSSSSsgGY..X.....',
        '..YGgsSSSSSSSSSgGYWXX...',
        '..GgAaSSSSSSSSSaAgGWXX..',
        '..GHAASSSSSSSSSAAHGkXX..',
        '..GHAASSSSSSSSAAaHGkXX..',
        '..GHAASSSSSSSSAAHG.WXX..',
        '...HAASSSSSSSSaaAHQWWXQ.',
        '...HAAStTTTtSAAAH..QQQ..',
        '....AAtTTTTTtAAAH...Q...',
        '....AAtTTTTTtAAA........',
        '......LlllllllL.........',
        '......LlllAllllL........',
        '......Ll.....llL........',
        '......kk.....kkK........',
        '......KK.....KKK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#0a1008', c: '#385040', C: '#485848', d: '#304038', D: '#586858',
        p: '#607858', P: '#486048', v: '#506050', V: '#607060',
        s: '#405848', S: '#506058', a: '#384040', A: '#303838',
        g: '#607858', G: '#486048', Y: '#708868',
        R: '#1a2018', r: '#283028', q: '#384038',
        T: '#485040', t: '#585848', J: '#484848', H: '#586058',
        L: '#505848', l: '#606858', K: '#484848', k: '#585858',
        W: '#80a068', X: '#90b070', Q: '#709060', Z: '#a0c078',
        f: '#e0b888', F: '#c8a070', z: '#a88058',
      },
      grid: [
        '......PPPPppp...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGY..Z....',
        '.RYGgsSSSSSSSSSgGYZXX...',
        '.R.GgAaSSSSSSSsaAgGZXX..',
        '.r.GHAASSSSSSSSSAHGZWXX.',
        '.r.GHAASSSSSSSSAAHGZWXX.',
        '.r.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA...Q..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#0a1008', c: '#406048', C: '#507058', d: '#385040', D: '#607868',
        n: '#80b858', N: '#70a040', M: '#608830',
        v: '#607060', V: '#708070',
        s: '#486050', S: '#587060', a: '#404848', A: '#384040',
        g: '#709060', G: '#608050', Y: '#80a068',
        R: '#283830', r: '#384040', q: '#485048',
        T: '#586048', t: '#686858', J: '#585858', H: '#687068',
        L: '#606860', l: '#707870', K: '#585858', k: '#687068',
        W: '#90b078', X: '#a0c080', Q: '#809060', Z: '#b0d090',
        u: '#70a050', U: '#608840',
        f: '#e0b888', F: '#c8a070', z: '#a88058',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGYuZ.....',
        '.RYGgsSSSSSSSSSgGUZXX...',
        '.R.GgAaSSSSSSSSaAgUZWXX.',
        '.r.GHAASSSSSSSSSAHUZWXX.',
        '.r.GHAASSSSSSSSAAHUZWXX.',
        '.q.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  cleric: {
    3: {
      pal: {
        o: '#284028', c: '#d8e0f0', C: '#e8f0ff', d: '#c0c8e0', D: '#f0f8ff',
        p: '#f0d848', P: '#e0c038', v: '#f0d848', V: '#e0c038',
        s: '#d0d8e8', S: '#e0e8f8', a: '#c0c8d8', A: '#b0b8c8',
        g: '#f0d040', G: '#d8b828', Y: '#f8e060',
        T: '#e8e8c8', t: '#d8d8b0', J: '#609060', H: '#b0b8c8',
        E: '#e8d040', e: '#f0d848',
        L: '#c0c8c0', l: '#d0d0c8', K: '#a8b0a8', k: '#b8c0b0',
        W: '#f0e8a0', X: '#f8f0b0', Q: '#e0d020',
        f: '#f8e0b8', F: '#e8d0a0', z: '#d0b890',
        w: '#fff8f0', m: '#d07870',
      },
      grid: [
        '........................',
        '.......PPPppp...........',
        '......PGGGGGPo..........',
        '.....oDDDDDDDDo.........',
        '.....oCCCCCCCCo.........',
        '.....oCDDDDDCCo.........',
        'eE....offffffo..........',
        'eEE...zffffffzz.........',
        'eEE...zfwwwfeFzz........',
        'eEE...zffffffFz.........',
        'eEE...zzfmmfFzz.........',
        'eEE....zzFFzz...........',
        'eEE.YGgsSSSSSsgGY.......',
        'eE.YGgsSSSSSSSSSgGY.X...',
        'eE.GgAaSSSSSSSSSaAGkW...',
        'eE.GHAASSSSSSSSSAAHGkWW.',
        'ee.GHAASSSSSSSSSAAHGXWXQ',
        '.e..HAASSSSSSSAAAH...QQ.',
        '....HAAStTTTtSAAH..QQ...',
        '.....AAtTTTTTtAAA.......',
        '.....AAtTTTTTtAA........',
        '......LlllAllllL........',
        '......LlllAllllL........',
        '......Ll.....llL........',
        '......kk.....kkK........',
        '......KK.....KKK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#284028', c: '#e0e8f8', C: '#f0f8ff', d: '#c8d0e8', D: '#ffffff',
        p: '#f8e050', P: '#e8d040', v: '#f8e050', V: '#e8d040',
        s: '#d8e0f0', S: '#e8f0ff', a: '#c8d0e0', A: '#b8c0d0',
        g: '#f8e048', G: '#e0c830', Y: '#fff060',
        R: '#e8d040', r: '#f0d848', q: '#f8e050',
        T: '#f0f0d8', t: '#e0e0c0', J: '#709870', H: '#c0c8d8',
        E: '#f0d848', e: '#f8e050',
        L: '#c8d0c8', l: '#d8d8d0', K: '#b0b8a8', k: '#c0c0b0',
        W: '#f8f0a8', X: '#fff8b0', Q: '#e8e020', Z: '#ffea50',
        f: '#f8e0b8', F: '#e8d0a0', z: '#d0b890',
        w: '#fff8f0', m: '#d07870',
      },
      grid: [
        '.......PPPPppp..........',
        '......PPpppppp..........',
        '......oPPpPPo...........',
        '.....oDDDDDDDDo.........',
        '.....oCCCCCCCCo.........',
        '.....oCDDDDDCCo.........',
        '.R.eE.offffffo..........',
        '.R.eE.zffffffzz.........',
        '.R.eE.zfwwwfeFzz........',
        '.R.eE.zffffffFz.........',
        '.R.eE.zzfmmfFzz.........',
        '.RYeEgsSSSSSsSGGY.Z.....',
        '.r.eEgsSSSSSSSSSgGYZX...',
        '.r.eEAaSSSSSSSSSaAGZWX..',
        '.r.eEHAASSSSSSSAAHGZWX..',
        '.q.eEHAASSSSSSSAAHGkQWXQ',
        '.q.ee.HAaSSSSSaAAH..QQQ.',
        '.q....HAAStTtSAAH...Q...',
        '.q.....AAtTTTtAAA.......',
        '.q.....AATTaTTTAA.......',
        '..q.....aSSSSSaA........',
        '..q....llAAAAAAll.......',
        '..q....llA...Aall.......',
        '..q....kk.....kkl.......',
        '.......kk.....kkK.......',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#284028', c: '#e8f0ff', C: '#f8ffff', d: '#d0d8f0', D: '#ffffff',
        n: '#fff060', N: '#f0e040', M: '#e0d030',
        v: '#fff060', V: '#f0e040',
        s: '#e0e8f8', S: '#f0f8ff', a: '#d0d8e8', A: '#c0c8d8',
        g: '#fff050', G: '#f0e038', Y: '#fff870',
        R: '#f0e040', r: '#f8e848', q: '#fff050',
        T: '#f8f8e8', t: '#e8e8d0', J: '#80a880', H: '#d0d8e8',
        E: '#f8e848', e: '#fff050',
        L: '#d0d8d0', l: '#e0e0d8', K: '#b8c0b8', k: '#c8c8c0',
        W: '#fff8b0', X: '#fffff0', Q: '#f0f020', Z: '#ffff80',
        u: '#f0e838', U: '#e0d820',
        f: '#f8e0b8', F: '#e8d0a0', z: '#d0b890',
        w: '#fff8f0', m: '#d07870',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDDo.........',
        '.....oCCCCCCCCo.........',
        '.....oCDDDDDCCo.........',
        '.R.eE.oVVvvVVVo.........',
        '.R.eE.offffffo..........',
        '.R.eE.zfwwwfeFzz........',
        '.R.eE.zffffffFz.........',
        '.R.eE.zzfmmfFzz.........',
        '.RYeEgsSSSSSsSGGY.......',
        '.r.eEgsSSSSSSSSSgGY.....',
        '.r.eEAaSSSSSSSSSaAGuZX..',
        '.r.eEHAASSSSSSSAAHGuZWX.',
        '.q.eEHAASSSSSSSAAHGUZWX.',
        '.q.ee.HAaSSSSSaAAH.QWWQ.',
        '.q....HAAStTtSAAH..QQQ..',
        '.q.....AAtTTTtAAA..QQ...',
        '.q.....AATTaTTTAA.......',
        '..q.....aSSSSSaA........',
        '..q....llAAAAAAll.......',
        '..q....llA...Aall.......',
        '..q....kk.....kkl.......',
        '.......kk.....kkK.......',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  fighter: {
    3: {
      pal: {
        o: '#181018', c: '#a07850', C: '#b88860', d: '#887040', D: '#c89870',
        p: '#c07830', P: '#a06020', v: '#c07830', V: '#d08840',
        s: '#b08858', S: '#c0a070', a: '#907050', A: '#786040',
        g: '#d0a030', G: '#b88020', Y: '#e0b040',
        T: '#a06838', t: '#b07848', J: '#604830', H: '#907050',
        L: '#907058', l: '#a08068', K: '#685040', k: '#786050',
        W: '#c0c8d0', X: '#d0d8e0', Q: '#c0a030',
        f: '#f0c898', F: '#dab080', z: '#c09060',
      },
      grid: [
        '........................',
        '.......ppppp............',
        '......PPpppPP...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.....oVVVVVVVo..........',
        '......odddddo...........',
        '......zzFFFzz...........',
        '...YGgsSSSSSsgGY..X.....',
        '..YGgsSSSSSSSSSgGYWXX...',
        '..GgAaSSSSSSSSSaAgGWXX..',
        '..GHAASSSSSSSSSAAHGkXX..',
        '..GHAASSSSSSSSAAaHGkXX..',
        '..GHAASSSSSSSSAAHG.WXX..',
        '...HAASSSSSSSSaaAHQWWXQ.',
        '...HAAStTTTtSAAAH..QQQ..',
        '....AAtTTTTTtAAAH...Q...',
        '....AAtTTTTTtAAA........',
        '......LlllllllL.........',
        '......LlllAllllL........',
        '......Ll.....llL........',
        '......kk.....kkK........',
        '......KK.....KKK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#181018', c: '#b08860', C: '#c09870', d: '#987048', D: '#d0a878',
        p: '#d08840', P: '#b07030', v: '#d08840', V: '#e09850',
        s: '#c09868', S: '#d0a878', a: '#a07858', A: '#887048',
        g: '#e0b040', G: '#c89828', Y: '#f0c050',
        R: '#303030', r: '#404040', q: '#505050',
        T: '#b07848', t: '#c08858', J: '#705040', H: '#a07858',
        L: '#a08068', l: '#b09078', K: '#786050', k: '#887060',
        W: '#d0d8e0', X: '#e0e8f0', Q: '#d0b040', Z: '#c0c8d8',
        f: '#f0c898', F: '#dab080', z: '#c09060',
      },
      grid: [
        '......PPPPppp...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGY..Z....',
        '.RYGgsSSSSSSSSSgGYZXX...',
        '.R.GgAaSSSSSSSsaAgGZXX..',
        '.r.GHAASSSSSSSSSAHGZWXX.',
        '.r.GHAASSSSSSSSAAHGZWXX.',
        '.r.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA...Q..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#181018', c: '#c09870', C: '#d0a880', d: '#a88058', D: '#e0b888',
        n: '#e0b040', N: '#d0a030', M: '#c09020',
        v: '#e09850', V: '#d08840',
        s: '#d0a878', S: '#e0b888', a: '#b08860', A: '#a07850',
        g: '#f0c050', G: '#d8a838', Y: '#ffd060',
        R: '#383838', r: '#484848', q: '#585858',
        T: '#c08858', t: '#d09868', J: '#786050', H: '#b08868',
        L: '#b09078', l: '#c0a088', K: '#887060', k: '#988070',
        W: '#e0e8f0', X: '#f0f0ff', Q: '#e0c050', Z: '#d8e0f0',
        u: '#d0a840', U: '#c09830',
        f: '#f0c898', F: '#dab080', z: '#c09060',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGYuZ.....',
        '.RYGgsSSSSSSSSSgGUZXX...',
        '.R.GgAaSSSSSSSSaAgUZWXX.',
        '.r.GHAASSSSSSSSSAHUZWXX.',
        '.r.GHAASSSSSSSSAAHUZWXX.',
        '.q.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },

  berserker: {
    3: {
      pal: {
        o: '#200808', c: '#982020', C: '#b02828', d: '#801818', D: '#c03030',
        p: '#e04040', P: '#c83030', v: '#e83030', V: '#d02020',
        s: '#a02828', S: '#b83030', a: '#882020', A: '#781818',
        g: '#d03020', G: '#b02010', Y: '#e04030',
        T: '#202020', t: '#303030', J: '#401818', H: '#802020',
        L: '#602020', l: '#703030', K: '#501010', k: '#602020',
        W: '#c83020', X: '#d84030', Q: '#b02818',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '........................',
        '.......ppppp............',
        '......PPpppPP...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.....oVVVVVVVo..........',
        '......odddddo...........',
        '......zzFFFzz...........',
        '...YGgsSSSSSsgGY..X.....',
        '..YGgsSSSSSSSSSgGYWXX...',
        '..GgAaSSSSSSSSSaAgGWXX..',
        '..GHAASSSSSSSSSAAHGkXX..',
        '..GHAASSSSSSSSAAaHGkXX..',
        '..GHAASSSSSSSSAAHG.WXX..',
        '...HAASSSSSSSSaaAHQWWXQ.',
        '...HAAStTTTtSAAAH..QQQ..',
        '....AAtTTTTTtAAAH...Q...',
        '....AAtTTTTTtAAA........',
        '......LlllllllL.........',
        '......LlllAllllL........',
        '......Ll.....llL........',
        '......kk.....kkK........',
        '......KK.....KKK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    4: {
      pal: {
        o: '#200808', c: '#a82828', C: '#c03030', d: '#902020', D: '#d03838',
        p: '#e84848', P: '#d03838', v: '#f03838', V: '#e02828',
        s: '#b03030', S: '#c83838', a: '#983030', A: '#882020',
        g: '#e03828', G: '#c02818', Y: '#f04838',
        R: '#280808', r: '#381010', q: '#481818',
        T: '#282020', t: '#383030', J: '#482020', H: '#903030',
        L: '#703030', l: '#804040', K: '#602020', k: '#703030',
        W: '#d84030', X: '#e85040', Q: '#c03028', Z: '#f06050',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '......PPPPppp...........',
        '.....PPpppppp...........',
        '......oPPpPPo...........',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGY..Z....',
        '.RYGgsSSSSSSSSSgGYZXX...',
        '.R.GgAaSSSSSSSsaAgGZXX..',
        '.r.GHAASSSSSSSSSAHGZWXX.',
        '.r.GHAASSSSSSSSAAHGZWXX.',
        '.r.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA...Q..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
    5: {
      pal: {
        o: '#200808', c: '#c03030', C: '#d84040', d: '#a82020', D: '#e85050',
        n: '#f05050', N: '#e04040', M: '#d03030',
        v: '#f84040', V: '#e83030',
        s: '#c83838', S: '#d84848', a: '#a83030', A: '#983020',
        g: '#f04838', G: '#d83828', Y: '#ff5848',
        R: '#300808', r: '#401010', q: '#501818',
        T: '#302828', t: '#403838', J: '#502828', H: '#a03838',
        L: '#804040', l: '#905050', K: '#703030', k: '#804040',
        W: '#e85050', X: '#f86060', Q: '#d84040', Z: '#ff7070',
        u: '#e04040', U: '#d03030',
        f: '#f0c898', F: '#dab080', z: '#c09060',
        e: '#181830', w: '#f0e8e0', m: '#d07868',
      },
      grid: [
        '...N.nMNMn.N............',
        '....NnMMMnNN............',
        '......oNMNo.............',
        '.....oDDDDDDDo..........',
        '.....oCCCCCCCo..........',
        '.....oCCDDDCCo..........',
        '.R...oVVVVVVVo..........',
        '.R....odddddo...........',
        '.R....zzFFFzz...........',
        '.RYGGgsSSSSSsSGGYuZ.....',
        '.RYGgsSSSSSSSSSgGUZXX...',
        '.R.GgAaSSSSSSSSaAgUZWXX.',
        '.r.GHAASSSSSSSSSAHUZWXX.',
        '.r.GHAASSSSSSSSAAHUZWXX.',
        '.q.GHAASSSSSSSSAAHG.WXX.',
        '.q..HAASSSSSSSAAAH.QWWXQ',
        '.q..HAAStTTTtSAAAH..QQQ.',
        '.q...AAtTTTTTTtAAA..QQ..',
        '.q...AATTTaTTTTAA.......',
        '.q....AaSSSSSsaA........',
        '..q...llAAAAAAll........',
        '..q...llA...Aall........',
        '..q...kk.....kkl........',
        '......kk.....kkK........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ]
    },
  },
};

// Cat sprite (Sushi)
export const CAT_PAL = {
  o: '#f0a858', O: '#e09040', r: '#d88030', w: '#f8e8d8',
  n: '#e06878', e: '#40c060', p: '#181828',
  k: '#c87828', t: '#f8d0a0', i: '#f0b868',
};

export const CAT_GRID = [
  '.oo..oo.................',
  'oiiooiio................',
  'oiioOiio................',
  'oepttpeO................',
  'ooontorr................',
  'rrtwwtOr................',
  '.rrOOrr.................',
  '..r..r..................',
];
